### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by galenhelt** [billthefarmer/notes#10]
Great program.  Is is possible, using the Template feature (or otherwise), to create a new note with the time and date stamp (automatically) on it?

**Comment by billthefarmer** [comment]
It should be possible to put something like `{{date}}`, or `{{date dd MMM yyyy  HH:mm}}` in a template and have it replaced by the current date/time. Patterns [here](https://developer.android.com/reference/java/text/SimpleDateFormat#date-and-time-patterns). I shall investigate.

**Comment by billthefarmer** [comment]
I have released a new version with a date code for the template. I have had to use angle brackets rather than curly brackets because of a conflict with the regular expression used for parsing. 

`<<date>>` or `<<date dd MMM yyyy HH:mm>>`
