### ISSUE TITLE
make the standard directory configurable

### ISSUE THREAD

**Issue by christfried** [billthefarmer/notes#17]
Please make the standard folder configurable. I want to use the app just as a markdown editor. Unfortunately, when I open a document with the app the formatting is broken so I need to use the app to open files. This only works for me, if I am able to set another folder as the standard folder ...

Thanks in advance!

**Comment by billthefarmer** [comment]
The app folder is configurable in the settings. It may not be immediately apparent because the built in file picker opens the folder of the current file. Use the built in file picker to open files, it will open files anywhere on the device where it has read permission.

**Comment by christfried** [comment]
This is what I meant: The file picker (folder icon on the top bar) always opens the standard directory "Notes". Then I have to go back and select the directory I really wanted to find the files inside. I am looking for a way to change this standard directory to a custom one so that I don't have to go back and navigate to my files all the time.

**Comment by billthefarmer** [comment]
Read what I wrote...

![notes](https://user-images.githubusercontent.com/3448386/107352974-683e9c00-6ac4-11eb-90ea-1e9dcd1a6c70.gif)

**Comment by christfried** [comment]
Thanks it is working now! (I am sorry but that was way too unintuitive to figure out. I would have been worried to overwrite stuff, if I would have thought about just using an existing folder name.)
Still -- I really appreciate your work!
