### ISSUE TITLE
Date inserted via menu item creates list (Germany specific?)

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/notes#2]
An Android formatted date in Germany, inserted via menu item looks like this: 
24. Februar 2020
The app seems to take that as a list item, (at least as far as I understand from knowing your quite similar structured Diary app) and transforms the "24." into "1.", in my case, for the first item in the list.

**Comment by billthefarmer** [comment]
That's because of the dot after the 24. That's in the markdown syntax definition, see https://daringfireball.net/projects/markdown/syntax#list. I don't know why the German date format does that, but there's not a lot I can do about it.

**Comment by uli-on** [comment]
I've experimented a little since I started the issue and found that a leading character, even a dot, disables the date getting converted into a list. So I added a `&zwnj;` and it worked as desired. But adding that to any date inserted would confuse people to hell and would certainly lead to people deleting it, maybe leaving remaining characters. Hence: Are there perhaps _invisible_ control characters "in Android" that might be used for disabling automatic list formatting for dates with dot separators?

**Comment by billthefarmer** [comment]
Control codes don't work well in android, I have found. One possibility is to put `#### ` in front so that it is displayed as a small header, like this...
#### 24. Februar 2020 10:20
```markdown
#### 24. Februar 2020 10:20
```
However, if I do that I will probably get issues raised by others...

**Comment by uli-on** [comment]
Or prepend the two-letter day-of-week? Cause 4x hash would also put formatting on the date and everything on that same paragraph, bolded, h4.

**Comment by billthefarmer** [comment]
The predefined options I am using format the date and time correctly for each language. Adding an extra field will probably break that for some languages, for example the English convention is three letter day of week.
