### ISSUE TITLE
No Markdown when 'Open with..'

### ISSUE THREAD

**Issue by wasu-code** [billthefarmer/notes#20]
When opening file from another app eg. File Manager it open file as plain text with edit option but it's impossible to see markdown formating neither as default nor after clicking any button.
It would be great if it worked that way too.

**Comment by wjg57** [comment]
This may be the same underlying issue: when I receive an email with a markdown document in an attachment, it would be nice to be able to open it in Notes.

Currently the selection to open it in Notes appears, but the application only flashes up very quickly and then disappears again.

Saving the attachment first and then opening it from Notes works, navigation to the file saved in a file manager opens the file in edit mode with no possibility to switch to view mode.

Other than that i appreciate the completeness of the program - even tables are rendered properly which frequently fails in other tools.

**Comment by billthefarmer** [comment]
The reason is that the app opens the editor used for editing styles and scripts. I shall investigate.
