### ISSUE TITLE
Mixed LTR RTL support?

### ISSUE THREAD

**Issue by muellert** [billthefarmer/notes#21]
I generally like this note app quite a bit, but am struggling to make it work with a mix of RTL and LTR text. I am not sure this is supposed to work, though, but I end up with all text on one line.

**Comment by billthefarmer** [comment]
I've made no provision for mixed direction text in any of my apps. It's possible, according to the [docs](https://developer.android.com/reference/android/view/View.html#attr_android:textDirection) in the edit view. I have tested this on my tablet. In the markdown view the text appears RTL regardless. Is this what you expect to happen?

![Screenshot_20210810-104618_Notes 1](https://user-images.githubusercontent.com/3448386/128845970-072dc036-8046-423a-a77c-74e3dd55c162.jpg)

![Screenshot_20210810-104634_Notes 1](https://user-images.githubusercontent.com/3448386/128846130-80bb96bc-5fbc-4870-ab5f-b55877506dbf.jpg)

**Comment by billthefarmer** [comment]
The problem with the markdown view may be due to specifying the language in the HTML header, which is picked up from the language the device is set to.
