### ISSUE TITLE
A layout adaptation problem

### ISSUE THREAD

**Issue by yuhuitech** [billthefarmer/notes#22]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the about page, **some texts could not be seen fully, and this page is not scrollable**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.17, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on this page, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the about button, which is the last on the settings page
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128962869-6043e996-8975-4696-9cc7-81df950f1e5f.png" alt="Screenshot_1628650441 copy" width="250"/>

**Environment**

1. Version of Notes : 1.17
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by billthefarmer** [comment]
You seem to be somewhat unlucky. I tried on my fairly small Moto G and a Pixel emulator and they both come out OK. I shall investigate.

![Screenshot_1628667675](https://user-images.githubusercontent.com/3448386/128989820-14d25b69-d642-4afa-9735-95407f13339c.png)
