### ISSUE TITLE
Several typos in the German strings

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/notes#24]
Here's the revised lower thirds of the German strings (the first two thirds were OK), taken from https://raw.githubusercontent.com/billthefarmer/notes/master/src/main/res/values-de/strings.xml, for simplicity's sake everything below the copyright string down to the very end:

```

  <string name="choose">Wähle einen Dateinamen</string>
  <string name="loading">Laden…</string>

  <string name="modified">
    Du hast ungespeicherte Änderungen. Möchtest Du Deine Änderungen speichern?
  </string>

  <string name="changedReload">
    Diese Datei hat sich geändert, möchtest Du sie neu laden?
  </string>

  <string name="changedOverwrite">
    Diese Datei hat sich geändert, möchtest Du sie überschreiben?
  </string>

  <string name="ok">OK</string>
  <string name="reload">Neu laden</string>
  <string name="overwrite">Überschreiben</string>
  <string name="discard">Verwerfen</string>
  <string name="cancel">Abbrechen</string>

</resources>

```

 In the context they were in, two of these strings sounded like machine translations of single words, trying to amend/adopt to existing German phrases. Should you need some strings translated in their context you can always contact me, be it for Notes, Diary or Editor, which I know quite well :)

EDIT: I'll stay subscribed here, so you could simply reply for notifying me.

**Comment by billthefarmer** [comment]
Thank you, I have made the changes.

**Comment by billthefarmer** [comment]
One of the things that happens is that immediately after I have published a new release, someone comes up with a bug or a change, so I incorporate it into the release in the hope that F-Droid will pick it up when they get around to building the app. That's what happened this time and it must have not worked.

**Comment by uli-on** [comment]
Thanks for answering, it's not a big thing. Just wanted to let you know,
cause you won't have German activated :)

Am 14. September 2021 19:02:24 schrieb Bill Farmer ***@***.***>:
