### ISSUE TITLE
[Question] regarding cursor position 

### ISSUE THREAD

**Issue by 3504k** [billthefarmer/notes#25]
Using 1.19 from Fdroid. I noticed a newer version has been released recently.

Using Android 11

- I searched all issues for keyword "cursor"
- I followed steps from Help 

```You may put a line in a note to control or remember the edit cursor position. This will not appear in the markdown view. Put [<]: # on a line for the start of an note, [>]: # for the end of a note. Put [#]: # for the cursor position to be remembered. There should be no other text on the line. The current cursor position will be added when the note is saved [#]: # (nnn). Because notes are only saved if they are changed, moving the cursor with no other change will not move the saved position.```

- when I put exactly this ```[>]: #``` at the beginning or end of a note, on its own line, and change some text then hit save, the cursor position in edit mode doesn't get placed at the end of the note. When I share from another app, the shared text or link also is not placed at the end of the note.

I believe I might be misinterpreting your help document, and that this isn't a bug.

Thank you so much for your help.

Edit: my note is

```
&nbsp;

&nbsp;

&nbsp;

## [Help](help.md)

## [Book list](booklist.md)

## [Simpletask to-do](simpletasktodo.txt)

## [Simpletask archive](done.txt)

## [Bookmarks](Bookmarks.md)

## [ublockfilters_2021-09-16.txt](file:///storage/emulated/0/Notes/ublockfilters_2021-09-16.txt) 

[>]: #
```

**Comment by billthefarmer** [comment]
This is an omission, it will be fixed in the next version.

**Comment by 3504k** [comment]
Looks like your commit will fix this. Still waiting on fdroid release, but I don't see any reason to leave this open unless you still want it open. 

Thanks for your awesome apps.
