### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [billthefarmer/notes#3]
Can the app be translated? With something like weblate, poeditor, crowdin or transifex.

**Comment by billthefarmer** [comment]
Yes, anyone can submit a translation, either by forking the app and adding their translation in `~/src/main/res/values-<language code>/strings.xml` or by putting the translation in an issue so I can add it.
See https://developer.android.com/guide/topics/resources/localization#creating-alternatives.

**Comment by Cwpute** [comment]
would you consider using crowdsourcing tools for users who're not familiar with git ?

**Comment by mondlicht-und-sterne** [comment]
> would you consider using crowdsourcing tools for users who're not familiar with git ?

[Crowdin](https://crowdin.com/) , [Weblate Codeberg](https://translate.codeberg.org/) or [Hosted Weblate](https://hosted.weblate.org/)
