### ISSUE TITLE
Add template for the new note name (current date & time)

### ISSUE THREAD

**Issue by lucker999** [billthefarmer/notes#30]
Hello Bill, 

Thank you for the app. I love the simplicity of it and the function set is just right for me, nothing is bloated. I use it to take quick notes and catch ideas on-the-go to process them later.

Would it too much to ask you to add a new feature? I would like to have a **template for the new note name**. In particular, would be awesome to apply the same SimpleDateFormat for that. It would be very useful for taking quick notes, which could happen many times a day, but the hassle to name all them is somewhat hinders the idea of quick note taking :)

Or, another one: could you please add a simple widget as well? Just a button to open new note in editing mode (from the Template.md), nothing fancy.

**Comment by billthefarmer** [comment]
OK, good idea, I would propose to use the a similar format as dates in a note template. So `<<date>>.md` would generate `Notes/2022/02/18-194531.md`. This generates a hierarchical folder tree like my [Diary](https://github.com/billthefarmer/diary) app. Or you can use your own date template `<<date yyyy/MM/Note-ddHHmmss>>.md`, for example.

![Screenshot_20220218-195903 1](https://user-images.githubusercontent.com/3448386/154753159-906a31a4-f9b7-4ad8-8e58-4384b57fc3ce.png)

 A widget should be OK.

**Comment by lucker999** [comment]
Sorry for the delayed response and thank you so much for the prompt answer. 

The solution you proposed (and looks like have already implemented) is the best possible way to achieve what I was hoping for! I really like it and looking forward to use it (slightly impatiently :))!

**Comment by lucker999** [comment]
Finally the update has arrived to F-Droid. Works as expected, thank you so much Bill, appreciate that!

One more thing: could it be possible to open a new note in editing mode instead of reading? At least for one created with the widget. Couldn't find in setting such option...

**Comment by lucker999** [comment]
Bill, there is one little final touch I would like to ask about: make focus on the new open note from the widget, so the keyboard pops up.

**Comment by lucker999** [comment]
Well, there is a problem: The template for the file name creates a name with a date, but also adds a space before the filename, which makes such files unsyncable.
Could you please fix this?

**Comment by billthefarmer** [comment]
I don't know where your space comes from, it's not in the template. I can't reproduce that.

**Comment by lucker999** [comment]
You are absolutely right, it comes from the template:

`<<date yyyy.MM.dd HH:mm>>` - create the space before the name in the new filename
`<<dateyyyy.MM.dd HH:mm>>` - no space before the date is created

Thank you for pointing that out, had no idea that it would possibly work without the space in the template.

**Comment by billthefarmer** [comment]
I have updated the template so that leading spaces are ignored.

**Comment by Friptick** [comment]
This was a great feature suggestion, very useful for on-the-fly notes.

The holy-grail workflow for this could in theory have only 3 steps:

1. One tap to open a new note in edit view - the widget and filename template make this possible :heavy_check_mark:
2. Type note :heavy_check_mark: 
3. One tap to save the note and make it go away :orange_square: - _almost_  perfect

Any chance of adding a button for step #3? ideally to "Save and close" but "Save" would be great. Anything's better than fishing in a menu.

Sorry for being greedy, it's just that your app is so close to the holy grail here. No other comes close, have tried them all. :smile: 

Thanks for considering, and for your work.

**Comment by billthefarmer** [comment]
The save button appears as soon as you make a change, otherwise it is redundant.

![Screenshot_20221102-102857 1](https://user-images.githubusercontent.com/3448386/199467014-047c8d4f-f18d-4e1b-a99b-574ddf23e70d.png)

**Comment by Friptick** [comment]
Ah, that's interesting because I don't have that Save button at all.

Using version 1.31 on Android 9. Could this be the reason?

**Comment by billthefarmer** [comment]
The save button has been there since the app was written. It hasn't changed since. Do you mean it's in the menu? If so that's down to android and the phone manufacturer. You usually get three buttons on a phone in the toolbar, four in landscape, more on tablets. I deliberately test my apps on an old Moto G, ten-ish years old and android 7, five years old to pick up any performance issues, etc on older kit.

![Screenshot_20221102-131956 1](https://user-images.githubusercontent.com/3448386/199500262-e78ce01b-029e-4ef8-98d9-c215a3c8f558.png)

**Comment by Friptick** [comment]
OK. That is odd. I can confirm that on opening the app on my device it looks exactly like your second-last screenshot (the portrait view) above. Basically identical, text size and icon proportions are exactly the same, **except** that is no disk icon. Just the "+" and the vertical ellipsis. There's loads of space for it (as you can see in your screenshot), but it's not there.

Device is a 5 y.o. Samsung J7 with 5.5 in. screen running Android 9.
