### ISSUE TITLE
Feature Request: ability to change default note on startup

### ISSUE THREAD

**Issue by pod5tr45** [billthefarmer/notes#32]
Current behavior: Notes always opens with Notes.md

It might be beneficial to be able to open something like home.md or tasks.md on startup instead.

For example, if a user primary uses Notes for tasks or to-do and doesn't want those things to go in the Notes.md file, and would rather open something named differently on startup.

I know you're keeping the app lean, but this didn't sound too crufty to me, but maybe it is to you.

Thanks for the wonderful app.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by pod5tr45** [comment]
Thanks, this works perfectly in v. 1.24

Cheers!
