### ISSUE TITLE
scripting help

### ISSUE THREAD

**Issue by McJoe21** [billthefarmer/notes#33]
Can I get help on the ids and stuff and examples of usage

**Comment by billthefarmer** [comment]
I'm not sure what you mean. If you means ids of HTML elements displayed in the web view, there are none. The [commonmark](https://github.com/commonmark/commonmark-java) library produces simple HTML with no classes or ids. If you mean help with JavaScript, there are plenty of tutorials online.

**Comment by McJoe21** [comment]
```js
var write = document.write;
write('<script src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js></script>')
let path = location.pathname;
write(path)
```

This won't work help

**Comment by billthefarmer** [comment]
That doesn't work in a browser, possibly because of missing quotes round the URL.

**Comment by McJoe21** [comment]
Would that fix issues with Notes
