### ISSUE TITLE
[Feature Request] Enhanced Backup options

### ISSUE THREAD

**Issue by urmomsangus** [billthefarmer/notes#35]
KeePassDX has a feature where when you tap the upper left hamburger menu, you are given an option to "save a copy to..." which opens the built-in Android file manager and allows you to choose the location for backup. This location includes cloud storage locations that have the appropriate permissions to show in the file manager.

It would be nice to have a similar option accessed from your three-dot menu in the upper right. 

Options might include:

- selecting "Backup" will open file manager for choosing location every time.
- a toggle in settings to require "Backup" to ask location every time so users can still do a quick backup or choose to be asked
- choose backup folder separately in settings, although I don't know how that would work for cloud storage since the directory path has to be manually typed.
- (edit) two separate options in three-dot menu: "quick backup" and a "backup to..."

You have my sincerest thanks for the potential consideration of this request.

**Comment by billthefarmer** [comment]
This is possible. I would use a **Save As** type dialog so that by just tapping **Save** the backup would be saved in the default location, but with the option of entering a new path/name or using the android file manager by tapping **Storage**. This may take a while.

**Comment by urmomsangus** [comment]
This works well in newest version, thank you!
