### ISSUE TITLE
[bug] Issue when opening note stored in Dropbox via app

### ISSUE THREAD

**Issue by urmomsangus** [billthefarmer/notes#37]
Notes: 1.28 F-Droid
Device: Samsung Galaxy A53

I hesitate adding this issue because I'm guessing the main app intention is only to open locally stored notes.

Dropbox allows you to choose a device app to open text and markdown files, for files stored in Dropbox. Notes failes to succeed at doing this except under certain circumstances. 

- Notes works well on brand new install (i.e. first time launching Notes)
- Notes works well if I clear the app cache
- Notes works well if I have it open on a blank note before opening the Dropbox file. 

---

- Notes crashes if I had previously opened a note from Dropbox and swipe it away from my recents screen, then attempt to open another note from Dropbox.
- This creates a slow workflow: swipe away from recents, reopen Notes on a blank page, then switch back to dropbox to open the chosen file.

I'm guessing there is either an intended or unintended caching of the previous file which doesn't clear after swiping from the recent apps. 

I don't believe this is a Dropbox issue because Markor works 100% of the time with Dropbox, but since Notes is superior to use, I thought I would at least mention it here. 

Attempted fix: I used Notes default settings and then tried to change default note name and some other settings to no avail. 

Thanks for your help. 

Edit:  To clarify, This is when I am launching files directly from the Dropbox app. I haven't attempted to go through any file manager, yet.  

The Dropbox files are visible but inaccessible if I go through the inbuilt "storage" menu options in Notes.

**Comment by billthefarmer** [comment]
The reason you can't open markdown files using the **Storage** option is because the '.md' extension isn't recognised as a text file by the file picker. You can open text files and other files recognised as text in Dropbox. I am investigating the crash.

**Comment by billthefarmer** [comment]
OK, I've fixed the crash. In android 12 on a Pixel 3a you can open '.md' files using the file picker via storage, but on android 7.1 on a Moto G they are greyed out. It's down to whether android recognises them as 'text/markdown' or 'application/octet-stream'.

**Comment by urmomsangus** [comment]
Confirmed fixed in version 1.29, F-Droid. 

Thanks again.
