### ISSUE TITLE
[Feature Request] Underline, strikethrough, etc

### ISSUE THREAD

**Issue by acdel123** [billthefarmer/notes#38]
I have been trying out Notes. So far, so good. It's a great basic markdown editor/viewer.

I hope this is the right place to request new features.

I am not sure if they are in the original/current markdown specification. But it would be great if you could add support for rendering underline  and strikethrough.  The former is surrounded by ++, the latter by ~~.

A real bonus would be support of [markdown emoji](https://github.com/markdown-templates/markdown-emojis).

Thanks and regards

**Comment by billthefarmer** [comment]
Underline and strikethrough are possible as there are commonmark extensions. I noticed that the emojies are implemented with a JSON data file. A nice project would be to create a javascript script using this file to implement the emojies as an addon using the script feature in the app.

**Comment by billthefarmer** [comment]
I have added underline and strikethrough to my [MarkdownView](https://github.com/billthefarmer/MarkdownView) library, but [JitPack](https://jitpack.io/#billthefarmer/MarkdownView) appears to be too busy to build it. So I can't build a new version of Notes until that gets done. However I have written a fairly simplistic [emojies.js](https://github.com/billthefarmer/notes/blob/master/data/emojies.js) script which appears to work. It probably needs a bit of TLC from a JavaScript expert. There is also a [minimised](https://github.com/billthefarmer/notes/blob/master/data/emojies.min.js) copy.

**Comment by acdel123** [comment]
> I have added underline and strikethrough to my [MarkdownView](https://github.com/billthefarmer/MarkdownView) library, but [JitPack](https://jitpack.io/#billthefarmer/MarkdownView) appears to be too busy to build it. So I can't build a new version of Notes until that gets done. However I have written a fairly simplistic [emojies.js](https://github.com/billthefarmer/notes/blob/master/data/emojies.js) script which appears to work. It probably needs a bit of TLC from a JavaScript expert. There is also a [minimised](https://github.com/billthefarmer/notes/blob/master/data/emojies.min.js) copy.

This is great. I appreciate the very prompt review and update!

**Comment by billthefarmer** [comment]
OK, I have released a new version.

**Comment by acdel123** [comment]
> OK, I have released a new version.
> 

Just tried out new version 1.30 that showed up on fdroid.

The underline works as expected.

Strikethrough sort of works.

It strikes through text as desired when text is wrapped by ~~ .

But text wrapped with single ~ also appears as strikethrough. My understanding is that single ~ is for subscript.

**Comment by billthefarmer** [comment]
See https://github.com/commonmark/commonmark-java/issues/267.

**Comment by acdel123** [comment]
> See [commonmark/commonmark-java#267](https://github.com/commonmark/commonmark-java/issues/267).

Thanks for that info... very annoying that they did this.

**Comment by billthefarmer** [comment]
I can't find any reference to subscript or superscript in the commonmark spec. Other sites/guides differ, some say use `<sub>/<sup>`, or `_/^`, or `~/^`. [Github](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text) says use `<sub>/<sup>`.

**Comment by billthefarmer** [comment]
OK, I have added `^sup^` , <sup>sup</sup> and `~sub~`, <sub>sub</sub>. This breaks GitHub `~strike~`, ~strike~. This will be in the next version.

**Comment by acdel123** [comment]
> This will be in the next version.


Tested 1.31 from fdroid. I have a test file with all markdown tags that I am aware of that I use to test markdown apps. Everything in it appears to be working now.

Thank you for making these updates. It is very much appreciated!
