### ISSUE TITLE
When writing the screen moves

### ISSUE THREAD

**Issue by yhutoo** [billthefarmer/notes#4]
During writing the screen first moves down under the keyboard, then it moves up and down by one line at every key input.
This issue doesn't happen nor in Diary nor in Editor, nor in Shorty, nor in Crossword.
(2 identical) ASUS Zenfone 3, Android 6.0.1;
Works fine in VMOS v1.0.52 (emulating Android 5.1.1) in the above devices as host.
Thank You and best.

**Comment by uli-on** [comment]
I can confirm that for 
Android 6.0.1, Moto G4
Webview 80.0.3987.119
Also tested on two keyboards (OpenBoard from F-Droid and Swiftkey)

Precondition is enough text/returns to evoke scroll bars on the remaining screen.

**Comment by billthefarmer** [comment]
That's a good one. I hadn't noticed because I hadn't tried editing any long files. There's some sort of weird interaction going on, I shall investigate.

**Comment by yhutoo** [comment]
Fixed; but new issue:

After editing the changed text doesn't immediately appear switching to view mode; user must change file and come back to have the changes displayed in both views.

**Comment by billthefarmer** [comment]
I can't reproduce that &ndash; tested on three different devices with short and long files.

**Comment by yhutoo** [comment]
Doesn't happen sistematically, I though the issue was gone; but it just happened again in a 10.5 KB.
Tested in VMOS/Android 5: no same issue.

**Comment by billthefarmer** [comment]
The app uses a changed flag to determine whether the current file needs saving and whether to refresh the markdown view when the user switches views. This is to determine whether to show the save button in the toolbar and to avoid unnecessarily refreshing the markdown view. If you make a change, save the file, and then switch then this may happen.

**Comment by yhutoo** [comment]
I will switch view and then save, it's fine.
For me the issue is set. Thks & b.rgds.
