### ISSUE TITLE
Easy data loss through save as

### ISSUE THREAD

**Issue by BestYeen** [billthefarmer/notes#41]
The app is great, but I've lost important notes through the save as function.
From what I can see, it probably went like this:
1. new -> type some text -> save as notes/untitled.md (over many days, this was important text)
2. at a later point in time I needed new notes, so I did new -> and typed some text
... and I've hit save as again and accepted the default untitled.md.
At that point there was no indication that I'd be overwriting my old notes, and there was no traditional file dialog making me aware of it.

This is a design issue. The app should check whether a file would be overwritten and present the user with a confirmation dialog. :(

**Comment by billthefarmer** [comment]
There is a bug in the save check function which should direct attempts to save a new file to **Save as** to prompt the user to change the name. Fixed in the next version.

**Comment by BestYeen** [comment]
I did use "save as".
Is the "save as" prompt supposed to display a confirmation dialog if a target file with the name you've entered already exists?
That there was no such confirmation was the problem on my end. :)

**Comment by billthefarmer** [comment]
I had not envisaged that users would persist and deliberately save a note called `Untitled.md` created by the **New Note** button. I have made three changes, if a user has managed to save a note with a path that matches the **New note** path, it will be loaded when the **New note** button is tapped, if the user persists on tapping the save button in the **Save as** dialog with the default new note name they will be returned to the dialog, if the note exists an overwrite dialog will appear. 

To avoid all this , it is possible to use the new note template with a date pattern to create new note names that stand some chance of being different to previous ones.

**Comment by BestYeen** [comment]
The changes sound nice. :)

Regarding being a little stubborn and entering the same document name twice: A use case for your program is taking quick notes on my phone when other things are on my mind. If I give the document a name fitting to its topic (groceries.md, car.md, todo.md), the confirmation prompt will prevent accidents too. :)
