### ISSUE TITLE
Encoding issue (prefer UTF8?)

### ISSUE THREAD

**Issue by BestYeen** [billthefarmer/notes#42]
The following breaks the text:
1. start the app (editing Notes.md)
2. type: Achtung: Ü!
3. close the app
4. start the app again
5. the Ü is now mangled

I've often run into similar problems in Java when I wasn't very explicit about the encoding used for writing and reading text files. If there was an option to force saving and loading notes as UTF-8, I'd enable that and this kind of encoding problem would be gone. :)

**Comment by BestYeen** [comment]
I've dug up something from my Java project tree: Java file methods commonly have a java.nio.charset.Charset parameter, and in the Windows world I often have to use java.nio.charset.StandardCharsets.ISO_8859_1 ("Western", though the Euro symbol is in 8859-15) and .UTF_8, the latter being the most dependable for umlauts and everything else.

(This message was drafted in your program on my mobile phone, heh)

**Comment by billthefarmer** [comment]
The app had charset detection code from [ICU4J](https://unicode-org.github.io/icu/userguide/icu4j/), which appears to be unreliable. I have removed it. Android defaults to UTF-8.
