### ISSUE TITLE
Latest release did not include .apk

### ISSUE THREAD

**Issue by slaszt** [billthefarmer/notes#43]
As the title says. I am not a developer, so could you please either provide instructions on how to turn the .zip into an .apk or upload the .apk for me to install?

Great app so far, would love to try the latest version. Thanks.

**Comment by billthefarmer** [comment]
I have to wait for F-Droid to build it. You can always get the latest built version from [F-Droid](https://f-droid.org/packages/org.billthefarmer.notes).
