### ISSUE TITLE
Note is sometimes not opened via intent ("Open with")

### ISSUE THREAD

**Issue by dvmc** [billthefarmer/notes#44]
When trying to open a markdown note via a specific file manager (here: Simple File Manager Pro) with the Notes app as target application, the note is not opened, and instead you get an empty new note. However, when opening it with Editor (org.billthefarmer.editor), then the note is opened successfully, just without Markdown formatting.

Here is the intercepted intent which works with Editor, but not with Notes:

```
intent://media/external/file/47861#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;S.real_file_path_2=%2Fstorage%2Femulated%2F0%2FNotes%2FSrpska2023Daten.md;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://media/external/file/47861 
MIME: application/octet-stream 
URI: intent://media/external/file/47861#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;S.real_file_path_2=%2Fstorage%2Femulated%2F0%2FNotes%2FSrpska2023Daten.md;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
EXTRAS: 
1 Class: java.lang.String 
Key: real_file_path_2 
Value: /storage/emulated/0/Notes/Srpska2023Daten.md 

------------ 
MATCHING ACTIVITIES: 
Editor (org.billthefarmer.editor - org.billthefarmer.editor.Editor) 
Notes (org.billthefarmer.notes - org.billthefarmer.notes.Notes) 
```

And for the sake of completeness, here is the intercepted intent with another file manager (Android Files), which works with both Notes and Editor:

```
intent://com.android.externalstorage.documents/document/primary%3ANotes%2FSrpska2023Daten.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.android.externalstorage.documents/document/primary%3ANotes%2FSrpska2023Daten.md 
MIME: application/octet-stream 
URI: intent://com.android.externalstorage.documents/document/primary%3ANotes%2FSrpska2023Daten.md#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
MATCHING ACTIVITIES: 
Editor (org.billthefarmer.editor - org.billthefarmer.editor.Editor) 
Notes (org.billthefarmer.notes - org.billthefarmer.notes.Notes) 
```

**Comment by billthefarmer** [comment]
I have tested this with the two file managers on this device which work as expected. Android provides the FileProvider class for sharing files. Unfortunately there is no consistency with file managers.

**Comment by billthefarmer** [comment]
I have investigated further. Notes uses the [ContentResolver](https://developer.android.com/guide/topics/providers/content-providers) API to get the file display name to check the extension to see if it is a text or markdown file. This probably didn't work possibly because it wasn't implemented by the file manager.
