### ISSUE TITLE
[Enhancement Request] open as plain text?

### ISSUE THREAD

**Issue by 12425** [billthefarmer/notes#45]
Thanks for the great app that is the best to check all my notes!
Sometimes I just wanted to view some `.txt` files which doesn't follow markdown syntax, especially the single new lines will be ignored.
Can we detect the file extension a little bit? If it is `.txt`, can we display as plain text?
Or the other way around, display as markdown only for `.md`, `.markdown`?

I know you have another app `editor` which deals with plain text files, but I will appreciate if one app can handle both. Thanks again!

**Comment by StevanWhite** [comment]
Hi, Bill,

I, too, didn't care for the automatic interpretation as markdown.

The app advertises that it can take all sorts of TEXT types by sharing... but always interprets them as markdown.  
When the app is given a Python script, for example, it usually does very inappropriate things to it.
It is objectionable to interpret certain data as markdown.  It would be better to just display them as plain text, unless they are explicitly something else, such as markdown, or HTML, or SVG, or anything with a reasonable graphical representation.

There is, in principle, room in your app for a per-note MIME type.

It would mean an extra UI button for the user to choose a viewing mode, to see the underlying text or the marked up version, 
and internal handling of the mode for each note, as well as handling the type of incoming data.

I'm not suggesting that the app should be a programmer's text editor or SVG editor or anything...  
Just don't have the app do _wrong_ things.

**Comment by billthefarmer** [comment]
The app is a notebook with extended markdown and other features. It's not intended as a general purpose text editor. If you want a text editor, use one.
