### ISSUE TITLE
Lost updates to a file

### ISSUE THREAD

**Issue by boldandbusted** [billthefarmer/notes#47]
Howdy. I updated a file yesterday, and today my updates are gone.

How can I prevent this in the future? Happy to provide more context that I can. Thank you.

**Comment by billthefarmer** [comment]
The app does not automatically save files, you must save it either by using the save button in the toolbar or in response to the unsaved changes prompt if you quit the app. Using the home button/action or the recent apps button/action will defeat this and depending on further actions such as dismissing apps or shutting down will lose changes.
