### ISSUE TITLE
Data loss due to lack of autosave

### ISSUE THREAD

**Issue by linguisticmind** [billthefarmer/notes#49]
I lost some data today because it didn't occur to me that the app wouldn't autosave the file like the [Diary](https://github.com/billthefarmer/diary) app does. The app was killed in the background during the night, and when I opened it in the morning, half of the note that I didn't save was gone.

I use this app and also the [Diary](https://github.com/billthefarmer/diary) and [Editor](https://github.com/billthefarmer/editor) apps, and I enjoy all of them and I think they are great tools. But this was not a good experience.

I hope the autosave functionality can be added in a future version so that the behavior is consistent with that of the Diary app which has a very similar look and feel. Even the Editor app has this functionality, so it seems odd for the Notes app not to.

**Comment by billthefarmer** [comment]
If you close the app by any means, if it can, it will pop up a dialog asking to save or discard the file. If the app is in the background and gets closed by the system or by swiping it off the recents display it doesn't get a chance. Save your edits.

**Comment by linguisticmind** [comment]
I see. I just think it would be nice if the auto-save option was there in case you forget to save something. It's the kind of thing that is easy to forget, especially on a mobile app. Like, for example, if you're writing down something you thought of late in the evening before falling asleep.

Especially if you also use the Diary app that looks and feels very similar and you're used to not needing to manually save your edits there.
