### ISSUE TITLE
Enhancement idea: search all notes

### ISSUE THREAD

**Issue by clach04** [billthefarmer/notes#52]
Searching in the current note is possible but it doesn't look like a global search all notes in the current directory (recursively) is supported.

**Comment by billthefarmer** [comment]
I thought I responded to this yesterday, but it seems to be not here. **Find all** appears in the menu when searching &ndash; see https://github.com/billthefarmer/notes#toolbar.

![Screenshot_20240415-135214 1](https://github.com/billthefarmer/notes/assets/3448386/381115e6-3a67-449f-9b65-b7047c033a3f)
