### ISSUE TITLE
Missing error feedback hints

### ISSUE THREAD

**Issue by Kazaf123** [billthefarmer/notes#53]
**Description:**
When I want to use the app to search for information, if the information is not found, the app does not have any message to tell me that the search failed. This is shown in the figure below.

**Example:**
![image](https://github.com/billthefarmer/notes/assets/44084361/8c6b8024-d882-4351-b60f-3921ad95015a)

**Appreciate:**
I expected developers to add text or other symbolic hints as necessary.

**Comment by billthefarmer** [comment]
It's an incremental search, as soon as you type a character the focus will move to the first matching character which will be highlighted. If not, nothing happens, as expected.

**Comment by Kazaf123** [comment]
Thanks for explanation. I understand it.
