### ISSUE TITLE
feature request: open directory by default

### ISSUE THREAD

**Issue by leela52452** [billthefarmer/notes#6]
@billthefarmer by default app provides an option to create new file. its good but not good enough for me.
for example on markor app. specified directory will display all files if we tap or start app. this is only show stopper to migrate from markor. thank you.

**Comment by billthefarmer** [comment]
If you tap the Open icon you get a list of files. If you just installed the app there won't be any unless you go looking in other folders. If you select Open recent on the menu there won't be any either. Until you start using it. This app works the same way as any other editor. New for an empty untitled file, Open to open an existing one, Save to save changes to an exiting one, Save as to save with a different name.
