### ISSUE TITLE
Relative links don't always work

### ISSUE THREAD

**Issue by khorser** [billthefarmer/notes#7]
Hi, I have encounterred a couple of issues which apparently have something to do with the app's current directory.

1. The code `![my picture](./media/mypicture.jpg)` doesn't show the linked image. But if I insert the image via menu with its absolute path and then change it to the relative path it is displayed properly.

2. Relative links to other documents like `[see also](doc.md)` don't work if the source file is not in the Notes root directory.

**Comment by billthefarmer** [comment]
Links are currently relative to the Notes directory. I shall change it to the current open file directory.
