### ISSUE TITLE
sharing over bluetooth

### ISSUE THREAD

**Issue by th1j5** [billthefarmer/notes#8]
If I select sharing via bluetooth, everything works fine, but I don't get the format I want.

If I'm *not* in editing mode, I get a .png file.
If I'm in editing mode, I get a .html file.

Would it be possible to have more consistent behavior and maybe also the option to choose between them and mainly also the option to transfer the raw .md file itself?

Thank you for the good working app.

**Comment by billthefarmer** [comment]
It depends what you mean by consistent behaviour. In order to give users a choice, the app shares what is effectively a screenshot when displaying the markdown view, and shares the markdown text when in edit mode. The app has no control of what happens once the choice dialog pops up. For some reason sharing text via Bluetooth turns it it into HTML. I have been caught by that one before. You can check that by sharing with another app.

**Comment by th1j5** [comment]
From a user standpoint it's a bit surprising to receive a .png, but I can see the logic.

For the HTML, I see the problem and searched a bit around and there should be a [workaround](https://stackoverflow.com/questions/29907030/sharing-text-plain-string-via-bluetooth-converts-data-into-html) (I didn't dive into code, just an internet search).
Of course, I can understand if you don't have the time to go deeper into it.

I actually wanted to share this file with another app ([Material Files](https://github.com/zhanghai/MaterialFiles)), but due to a [bug](https://github.com/zhanghai/MaterialFiles/issues/257), bluetooth is not an option.
That's why I tried with your app and finally ended up emailing the file to myself...

So if this is a non-issue, you can close it.

Thanks for the quick response

**Comment by billthefarmer** [comment]
Sharing was a contribution to my [Diary](https://github.com/billthefarmer/diary) app that I copied when I built this app without giving it much thought. It's not something that I tend to use much. What would a user expect? I have done some testing, it's possible to share an image and the text and at least one app, email, picks up both, and it's possible to share both the text and the current file which turns up intact via Bluetooth.

**Comment by billthefarmer** [comment]
OK, I will include that in the next version.

**Comment by th1j5** [comment]
If you would want to do that, that would be a nice improvement!
But don't feel obliged (at least by me), it's something I probably won't use much either, it's just because of this bug in my file manager that I wanted to use this.

I'd rather like it to get that bug fixed, because a file manager is more universal usable than sharing via you're note app.

Anyway, thanks for the neat app.

PS: (I leave this issue open until you close it yourself, after implementation or not)
